version: "3.8"

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 8080:8080

  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - 3000:3000
    environment: 
      DB_URL: postgresql://postgres:postgres@database:5432/postgres

      # postgresql://USER:PASSWORD@HOST:PORT/DATABASE

  database:
    build: ./database
    restart: always
    ports:
      - 5432:5432

